# GitHub Sponsors usernames
github: []

# Patreon username
patreon: ""

# Open Collective username
open_collective: ""

# Ko-fi username
ko_fi: ""

# Tidelift platform name/package
tidelift: ""

# Community Bridge project
community_bridge: ""

# Liberapay username
liberapay: ""

# IssueHunt username
issuehunt: ""

# Buy Me a Coffee username
buy_me_a_coffee: ""

# Thanks.dev username
thanks_dev: ""

# Custom sponsorship or donation links
custom:
  - https://firststeptechnologyllc.com
