#!/usr/bin/env python3

"""
Generate a simple Compliance-as-Code report.

First Step Technology LLC
Compliance-as-Code Platform
"""

import json
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RULE_FILE = ROOT / "docs" / "examples" / "compliance-rule-example.json"
OUTPUT_FILE = ROOT / "docs" / "examples" / "compliance-report.md"


def load_rule():
    with RULE_FILE.open("r", encoding="utf-8") as file:
        return json.load(file)


def build_report(rule):
    return f"""# Compliance Report

Generated: {datetime.utcnow().isoformat()} UTC

---

## Framework

{rule["framework"]}

## Control

{rule["control_id"]}

## Title

{rule["title"]}

## Guidance

{rule["guidance"]}

## Agent Instruction

{rule["agent_instruction"]}

## Metadata

| Field | Value |
|-------|-------|
| Family | {rule["metadata"]["family"]} |
| Version | {rule["metadata"]["version"]} |
| Status | {rule["metadata"]["status"]} |
| Priority | {rule["metadata"]["priority"]} |

---

Generated by the First Step Technology LLC Compliance-as-Code Platform example.
"""


def main():
    rule = load_rule()
    report = build_report(rule)

    OUTPUT_FILE.write_text(report, encoding="utf-8")

    print(f"Report written to: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
